baseURL = "https://ton-utilisateur.github.io/ton-repo/"
languageCode = "fr"
title = "Mon Blog"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowWordCount = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "À propos"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Articles"
    url = "/posts/"
    weight = 2
