baseURL = "https://wilonweb.github.io/papermod-ongp/"
languageCode = "en-us"
title = "Mon Blog"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowWordCount = true
  disableFingerprinting = true
  disableSRI = true

[outputs]
home = ["HTML"]


[menu]
  [[menu.main]]
    identifier = "about"
    name = "À propos"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Articles"
    url = "/posts/"
    weight = 2
